### PR TITLE
Add groups view

### PR DESCRIPTION
**Pull request by tidoust**
The view gets generated from all features referenced throughout the pages. It needs to be enabled in the toc.json file. This view matches #127. The Media & Entertainment Interest Group recently requested it again to create some sort of "heat map" of what's going on.

The list is pretty raw for now: it features the name of the group, the relevant specifications (or features in these specifications) that the group is working on (or was working on), and links to pages where the specifications are mentioned for further details.

Changes to data files were needed to align group names with their official names.

README not yet updated.

### CODE REVIEW

**Comment by tidoust** [comment]
@xfq, @chrisn, the view would typically produce something like:

image

**Comment by chrisn** [comment]
This looks really good, a group-based view will be very helpful. It doesn't show the level of activity in the groups, which I think was a part of the request from M&E IG, but that's perhaps not something to indicate here in the roadmaps.

**Comment by tidoust** [comment]
@chrisn said

> It doesn't show the level of activity in the groups, which I think was a part of the request from M&E IG, but that's perhaps not something to indicate here in the roadmaps.

I propose to merge this for now and improve the view over time. Some indication of the level of activity would certainly fit there, the question being: how to measure and present it? For instance, that could be:

- Charter dates
- Spec milestones: the code can already do that but the problem is that many groups don't maintain milestone dates so we haven't enabled the feature yet.
- Github or mailing-list activity

**Comment by dontcallmedom** [comment]
re github/mailing list active, I have some of that in the [group activity monitor](https://w3c.github.io/cg-monitor/?wg)

**Pull request merged**
