### PR TITLE
Adding CSP3 to the list of publishing related specs

### PR DESCRIPTION
**Pull request by iherman**

### CODE REVIEW

**Comment by xfq** [comment]
Hmm... I don't think CSP L3 is well-deployed for the moment: https://www.chromestatus.com/features#csp3

**Comment by iherman** [comment]
True. But is a valid working draft and work that is planned to be take over from CSP2. For a WG whose charter ends in 2 years, isn't that the one we should be watchful of?

**Comment by xfq** [comment]
I agree that CSP3 is gaining traction and will supersede CSP2, but I don't think it's "Well-deployed and/or fully specified technologies" in its current status.

The [mobile roadmap](https://w3c.github.io/web-roadmaps/mobile/security.html) mentions CSP2 in the "Well-deployed technologies" section, because it's a REC and implemented by all major web browsers. Mentioning CSP3 may be useful too, but IMHO it should be in the "Technologies in progress" section.

**Comment by iherman** [comment]
You are right. I will make the changes, but only later (I have some high priority stuff to take care of).

**Comment by iherman** [comment]
@xfq, I have pushed a commit, moving CSP3 the section "Specifications in progress".

Thanks!

**Pull request merged**
