### PR TITLE
[mobile] Mention Input for workers and worklets

### LINKED ISSUE #413: Mention Input for Workers and Worklets
- Spec: https://wicg.github.io/input-for-workers/
- No implementation status yet

Discussed during the [Workshop on Web Games](https://www.w3.org/2018/12/games-workshop/report.html#latency).

Could be mentioned in User Interaction. And/Or Performance and Tuning.

### PR DESCRIPTION
**Pull request by tidoust**
Fixes #413.

### CODE REVIEW

**Comment by xfq** [comment]
The text looks good to me in general. Would it be useful to mention other use cases, like interactive animation or audio?

**Comment by tidoust** [comment]
I completed the list, linking to other specs that could be used in conjunction with this proposal to implement them. I took the opportunity to add support for a `data-linkonly` attribute to reference specs that we want to link to but don't want to see appear in the following table.

**Comment by tidoust** [comment]
I just realized that I actually forgot to push the updates!
(I thought I had pushed to a branch in my own fork of the repo, not to the W3C repo, anyway...).

**Comment by xfq** [comment]
Merged. Thank you!

**Pull request merged**
