### PR TITLE
Publ additions

### PR DESCRIPTION
**Pull request by iherman**
Added some more MO document references

### CODE REVIEW

**Comment by iherman** [comment]
@xfq @tidoust : I let this think in your able hand; no idea what those PR problems are!

**Comment by tidoust** [comment]
@iherman That pull request contains a lot of suspicous updates that belong to the `gh-pages` branch, not to the `master` branch, so I think you prepared it against the wrong branch...

The default branch is now `master`. The `gh-pages` is automatically generated, should not be touched manually, and should not be used as basis for pull requests.

I prepared pull request #98, which should contain the changes you wanted to make to the publishing roadmap. Please take a look!

**Comment by xfq** [comment]
I was about to resolve the merge conflicts by hand, but yes, maybe creating a new "clean" PR is better.

**Comment by iherman** [comment]
@tidoust thanks. But I do not really know what happened; I made a branch off the master branch. I may have made the mistake for the pull request.

To be sure I will delete the gh-pages branch on my local copy. I should not touch it...

**Comment by tidoust** [comment]
In that case, you indeed may have incorrectly merged the server's `gh-pages` branch into your local `master`, in which case you may want to get rid of your local `master` branch as well, because the problem will still exist on your machine otherwise... I'm sure there is a fantastic series of Git commands to issue to clean things properly. Personally, I'd drop my local copy and clone the repo again ;)

**Comment by tidoust** [comment]
PR #98 merged, closing this without merging as a result.

**Comment by iherman** [comment]
I actually almost never merge locally. I commit & push the separate branch, and I use Sourcetree's interface to start up a pull request. I expect that one went wrong and generated a PR to the gh-pages...

**Comment by tidoust** [comment]
OK. FWIW, a "pull" request is a "fetch" followed by a "merge", so you do "merge" locally whenever you "pull", see:
https://www.git-scm.com/docs/git-pull

**Comment by iherman** [comment]
... and I do a merge on the main branch only when the PR is accepted and merged on the server:-)

**Pull request closed without merging**
